repos:
  - repo: local
    hooks:
      - id: test
        name: dune test
        entry: dune test
        language: system
        always_run: true
        pass_filenames: false
      - id: fmt
        name: dune fmt
        entry: dune fmt --preview
        language: system
        always_run: true
        pass_filenames: false
